### **PCA reduces the number of variables or features in a data set while still preserving the most important information like major trends or patterns.**

### First we will import the libraries : and then the dataset.

In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [56]:
dataset = pd.read_csv("iris.csv")

In [57]:
dataset

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

Now check the null values are present or not in the dataset :

In [58]:
dataset.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

Now extracts the values of a dataset into a variable x in Python using the pandas library.

In [59]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [60]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [61]:
print(y)

['Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'V

In [62]:
from sklearn.preprocessing import StandardScaler #scaling the data using StandardScaler
sc = StandardScaler()
x_scaled = sc.fit_transform(x)
x_scaled  #  each feature has been centered around 0 and scaled to have unit variance.

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

### StandardScaler standardizes features by removing the mean and scaling to unit variance.

# Now **Principal Component Analysis (PCA)**

In [63]:
from sklearn.decomposition import PCA
pca = PCA(0.9)    #we can also use PCA(n_components = 2) : if we know that 2 component are contrubuting major portion of the dataset.
x_pca = pca.fit_transform(x_scaled)
x_pca

array([[-2.26470281,  0.4800266 ],
       [-2.08096115, -0.67413356],
       [-2.36422905, -0.34190802],
       [-2.29938422, -0.59739451],
       [-2.38984217,  0.64683538],
       [-2.07563095,  1.48917752],
       [-2.44402884,  0.0476442 ],
       [-2.23284716,  0.22314807],
       [-2.33464048, -1.11532768],
       [-2.18432817, -0.46901356],
       [-2.1663101 ,  1.04369065],
       [-2.32613087,  0.13307834],
       [-2.2184509 , -0.72867617],
       [-2.6331007 , -0.96150673],
       [-2.1987406 ,  1.86005711],
       [-2.26221453,  2.68628449],
       [-2.2075877 ,  1.48360936],
       [-2.19034951,  0.48883832],
       [-1.898572  ,  1.40501879],
       [-2.34336905,  1.12784938],
       [-1.914323  ,  0.40885571],
       [-2.20701284,  0.92412143],
       [-2.7743447 ,  0.45834367],
       [-1.81866953,  0.08555853],
       [-2.22716331,  0.13725446],
       [-1.95184633, -0.62561859],
       [-2.05115137,  0.24216355],
       [-2.16857717,  0.52714953],
       [-2.13956345,

In [64]:
pca.explained_variance_ratio_  # these are principle componenets

array([0.72962445, 0.22850762])

### Splitting the dataset into the training set and test set

In [65]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x_scaled,y ,test_size=0.35 , random_state=42)

In [66]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train , y_train)
# fits the k-Nearest Neighbors classifier to the training data x_train and the corresponding target labels y_train.

KNeighborsClassifier()

In [67]:
y_pred = knn.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[['Versicolor' 'Versicolor']
 ['Setosa' 'Setosa']
 ['Virginica' 'Virginica']
 ['Versicolor' 'Versicolor']
 ['Versicolor' 'Versicolor']
 ['Setosa' 'Setosa']
 ['Versicolor' 'Versicolor']
 ['Virginica' 'Virginica']
 ['Versicolor' 'Versicolor']
 ['Versicolor' 'Versicolor']
 ['Virginica' 'Virginica']
 ['Setosa' 'Setosa']
 ['Setosa' 'Setosa']
 ['Setosa' 'Setosa']
 ['Setosa' 'Setosa']
 ['Versicolor' 'Versicolor']
 ['Virginica' 'Virginica']
 ['Versicolor' 'Versicolor']
 ['Versicolor' 'Versicolor']
 ['Virginica' 'Virginica']
 ['Setosa' 'Setosa']
 ['Virginica' 'Virginica']
 ['Setosa' 'Setosa']
 ['Virginica' 'Virginica']
 ['Virginica' 'Virginica']
 ['Virginica' 'Virginica']
 ['Virginica' 'Virginica']
 ['Virginica' 'Virginica']
 ['Setosa' 'Setosa']
 ['Setosa' 'Setosa']
 ['Setosa' 'Setosa']
 ['Setosa' 'Setosa']
 ['Versicolor' 'Versicolor']
 ['Setosa' 'Setosa']
 ['Setosa' 'Setosa']
 ['Virginica' 'Virginica']
 ['Versicolor' 'Versicolor']
 ['Setosa' 'Setosa']
 ['Setosa' 'Setosa']
 ['Setosa' 'Setosa']


**Predicting the New Data**

In [72]:
new_data_point = [[0.2, 1, 6, 0.8]]
transformed_data_point = sc.transform(new_data_point)
pred = knn.predict(transformed_data_point)
print(pred)

['Versicolor']


# Confusion Matrix

**confusion matrix summarizes the performance of a classification model by showing the number of correct and incorrect predictions for each class.**

In [76]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[19  0  0]
 [ 0 17  0]
 [ 0  1 16]]


0.9811320754716981

In [77]:
accuracy_score(y_test, y_pred)

0.9811320754716981

In [78]:
# So accuracy is almost 98%.