###**Dataset is from Kaggle, and it includes :**

**start_time**: Time when recording started (not needed for prediction).

**FFT_0 to FFT_9:** Frequency features from Fast Fourier Transform to detect vibrations in freq. .

**Impulse_Factor:** Indicates sudden vibration possibly due to impacts or cracks.

**Clearance_Factor:** Shows looseness in the bearing, useful for detecting wear.

**Mean_Absolute_Change:** how much the vibration signal changes from one point to the next, higher values may indicate faults.

**Root_Mean_Square_of_First_Difference:** Vibration energy or strength of the differences between consecutive points in the signal.

**Shannon_Entropy:** Measures randomness in the signal, higher in faulty bearings.

**Energy:** Represents the total power in the vibration signal, higher energy may signal a defect.

**Form_Factor:** Describes signal shape to detect waveform abnormalities, large deviation means faulty.

**Zero_Crossing_Rate:** Counts how often the signal changes sign (from positive to negative or vice versa).

**Turning_Point_Ratio:** Measures how often the signal has peaks and valleys (local highs and lows).

**key:** Target label indicating the type of bearing condition
example :

1 → Normal (No defect)

2 = Inner Race Fault

3 = Outer Race Fault

4 = Ball Fault

5 = Combination Fault (e.g., Ball + Outer race)

6 = Severe Fault (Multiple major defects)

 importing essential Python libraries: :

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/Bearing Feature Extracted Full(new_one).csv")

In [ ]:
df.head() # Shows first 5 rows

start_time      FFT_0     FFT_1     FFT_2     FFT_3     FFT_4     FFT_5  \
0    0.000000  31.315536  0.026463  0.022552  0.020844  0.008484  0.011385   
1    0.000382  31.258407  0.064264  0.013386  0.012085  0.026802  0.041938   
2    0.000765  31.301679  0.050746  0.012241  0.027052  0.003939  0.010544   
3    0.001147  31.257833  0.009600  0.043856  0.057151  0.012073  0.022455   
4    0.001529  31.365595  0.023202  0.021665  0.021480  0.018160  0.023118   

      FFT_6     FFT_7     FFT_8  ...  Impulse_Factor  Clearance_Factor  \
0  0.038506  0.025452  0.019910  ...        1.016272          1.016272   
1  0.017024  0.029024  0.044788  ...        1.045820          1.045820   
2  0.035028  0.027375  0.020011  ...        1.022890          1.022890   
3  0.090118  0.028734  0.032152  ...        1.028446          1.028446   
4  0.031493  0.007047  0.009308  ...        1.015489          1.015489   

   Mean_Absolute_Change  Root_Mean_Square_of_First_Difference  \
0              0.006978                              0.008461   
1              0.020485                              0.025362   
2              0.008656                              0.010892   
3              0.014392                              0.016926   
4              0.006626                              0.008707   

   Shannon_Entropy     Energy  Form_Factor  Zero_Crossing_Rate  \
0         3.911994  19.614395    30.025117                0.52   
1         3.911795  19.550670    28.178667                0.50   
2         3.911975  19.597787    29.719099                0.48   
3         3.911913  19.545345    29.121952                0.48   
4         3.911993  19.677177    30.124962                0.48   

   Turning_Point_Ratio  key  
0                  1.0    1  
1                  1.0    1  
2                  1.0    1  
3                  1.0    1  
4                  1.0    1  

[5 rows x 23 columns]

In [ ]:
df.tail() # Shows last 5 rows

start_time      FFT_0     FFT_1     FFT_2     FFT_3     FFT_4  \
15691    0.998096  31.381943  0.033236  0.043602  0.095660  0.027803   
15692    0.998479  31.416487  0.071259  0.055610  0.048163  0.007604   
15693    0.998861  31.447781  0.079788  0.036521  0.077338  0.044098   
15694    0.999243  31.251608  0.152001  0.095570  0.055853  0.063271   
15695    0.999625  31.205873  0.058723  0.025041  0.012158  0.028456   

          FFT_5     FFT_6     FFT_7     FFT_8  ...  Impulse_Factor  \
15691  0.017960  0.034694  0.023606  0.015299  ...        1.088124   
15692  0.010377  0.032376  0.053074  0.044818  ...        1.039486   
15693  0.015345  0.055607  0.027757  0.066742  ...        1.066948   
15694  0.023454  0.099081  0.102241  0.095038  ...        1.061752   
15695  0.064219  0.138230  0.044438  0.022981  ...        1.068331   

       Clearance_Factor  Mean_Absolute_Change  \
15691          1.088124              0.037580   
15692          1.039486              0.024067   
15693          1.066948              0.031288   
15694          1.061752              0.029592   
15695          1.068331              0.030511   

       Root_Mean_Square_of_First_Difference  Shannon_Entropy     Energy  \
15691                              0.048895         3.911200  19.728939   
15692                              0.028759         3.911725  19.751639   
15693                              0.039489         3.911454  19.801686   
15694                              0.035722         3.911500  19.553583   
15695                              0.036077         3.911538  19.495012   

       Form_Factor  Zero_Crossing_Rate  Turning_Point_Ratio  key  
15691    26.261595                0.42                  1.0    6  
15692    28.046863                0.48                  1.0    6  
15693    26.774663                0.50                  1.0    6  
15694    26.264048                0.50                  1.0    6  
15695    27.060819                0.48                  1.0    6  

[5 rows x 23 columns]

drop the first column, since it is not needed for analysis.

In [ ]:
df = df.drop(df.columns[0], axis=1)
df.head()

FFT_0     FFT_1     FFT_2     FFT_3     FFT_4     FFT_5     FFT_6  \
0  31.315536  0.026463  0.022552  0.020844  0.008484  0.011385  0.038506   
1  31.258407  0.064264  0.013386  0.012085  0.026802  0.041938  0.017024   
2  31.301679  0.050746  0.012241  0.027052  0.003939  0.010544  0.035028   
3  31.257833  0.009600  0.043856  0.057151  0.012073  0.022455  0.090118   
4  31.365595  0.023202  0.021665  0.021480  0.018160  0.023118  0.031493   

      FFT_7     FFT_8     FFT_9  ...  Impulse_Factor  Clearance_Factor  \
0  0.025452  0.019910  0.013576  ...        1.016272          1.016272   
1  0.029024  0.044788  0.036681  ...        1.045820          1.045820   
2  0.027375  0.020011  0.032754  ...        1.022890          1.022890   
3  0.028734  0.032152  0.008920  ...        1.028446          1.028446   
4  0.007047  0.009308  0.004343  ...        1.015489          1.015489   

   Mean_Absolute_Change  Root_Mean_Square_of_First_Difference  \
0              0.006978                              0.008461   
1              0.020485                              0.025362   
2              0.008656                              0.010892   
3              0.014392                              0.016926   
4              0.006626                              0.008707   

   Shannon_Entropy     Energy  Form_Factor  Zero_Crossing_Rate  \
0         3.911994  19.614395    30.025117                0.52   
1         3.911795  19.550670    28.178667                0.50   
2         3.911975  19.597787    29.719099                0.48   
3         3.911913  19.545345    29.121952                0.48   
4         3.911993  19.677177    30.124962                0.48   

   Turning_Point_Ratio  key  
0                  1.0    1  
1                  1.0    1  
2                  1.0    1  
3                  1.0    1  
4                  1.0    1  

[5 rows x 22 columns]

In [ ]:
df.shape # give shape of the in matrix form.

(15696, 22)

In [ ]:
df.describe() # it will give statistics (mean, std, min, max, etc.) of each feature.

FFT_0         FFT_1         FFT_2         FFT_3         FFT_4  \
count  15696.000000  15696.000000  15696.000000  15696.000000  15696.000000   
mean      31.337489      0.075852      0.038685      0.037511      0.030003   
std        0.111275      0.077727      0.067280      0.060032      0.051795   
min       26.997756      0.000825      0.000231      0.000087      0.000125   
25%       31.296532      0.038107      0.013957      0.014162      0.011364   
50%       31.348691      0.061768      0.024708      0.025275      0.019285   
75%       31.392838      0.093823      0.042483      0.042342      0.031213   
max       31.843958      1.993679      1.908735      1.734402      1.390574   

              FFT_5         FFT_6         FFT_7         FFT_8         FFT_9  \
count  15696.000000  15696.000000  15696.000000  15696.000000  15696.000000   
mean       0.029541      0.042101      0.034294      0.030743      0.032362   
std        0.047212      0.044548      0.040483      0.038226      0.040286   
min        0.000087      0.000148      0.000403      0.000181      0.000166   
25%        0.011564      0.019916      0.014485      0.012094      0.011443   
50%        0.019270      0.031933      0.024227      0.020600      0.019986   
75%        0.031538      0.050017      0.040571      0.035726      0.038427   
max        1.225321      1.040032      0.926665      0.792521      0.793635   

       ...  Impulse_Factor  Clearance_Factor  Mean_Absolute_Change  \
count  ...    15696.000000      15696.000000          15696.000000   
mean   ...        1.061025          1.061025              0.023331   
std    ...        0.056189          0.056189              0.020324   
min    ...        1.007863          1.007863              0.002744   
25%    ...        1.019418          1.019418              0.007195   
50%    ...        1.038151          1.038151              0.014840   
75%    ...        1.088128          1.088128              0.035691   
max    ...        1.607745          1.607745              0.178712   

       Root_Mean_Square_of_First_Difference  Shannon_Entropy        Energy  \
count                          15696.000000     15696.000000  15696.000000   
mean                               0.029797         3.911416     19.664401   
std                                0.026714         0.001215      0.130677   
min                                0.003376         3.876124     14.799209   
25%                                0.008945         3.911282     19.606852   
50%                                0.018553         3.911887     19.667958   
75%                                0.045131         3.911986     19.729001   
max                                0.277259         3.912014     20.347267   

        Form_Factor  Zero_Crossing_Rate  Turning_Point_Ratio          key  
count  15696.000000        15696.000000         15696.000000  15696.00000  
mean      28.029970            0.502724             0.999999      3.50000  
std        2.301821            0.041461             0.000163      1.70788  
min       13.450177            0.320000             0.979592      1.00000  
25%       26.520999            0.480000             1.000000      2.00000  
50%       28.937262            0.500000             1.000000      3.50000  
75%       29.916921            0.520000             1.000000      5.00000  
max       30.711152            0.780000             1.000000      6.00000  

[8 rows x 22 columns]

checks if any feature/column has missing values.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15696 entries, 0 to 15695
Data columns (total 22 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   FFT_0                                 15696 non-null  float64
 1   FFT_1                                 15696 non-null  float64
 2   FFT_2                                 15696 non-null  float64
 3   FFT_3                                 15696 non-null  float64
 4   FFT_4                                 15696 non-null  float64
 5   FFT_5                                 15696 non-null  float64
 6   FFT_6                                 15696 non-null  float64
 7   FFT_7                                 15696 non-null  float64
 8   FFT_8                                 15696 non-null  float64
 9   FFT_9                                 15696 non-null  float64
 10  Crest_Factor                          15696 non-null  float64
 11  Shape_Factor   

In [ ]:
df.isnull().sum()

FFT_0                                   0
FFT_1                                   0
FFT_2                                   0
FFT_3                                   0
FFT_4                                   0
FFT_5                                   0
FFT_6                                   0
FFT_7                                   0
FFT_8                                   0
FFT_9                                   0
Crest_Factor                            0
Shape_Factor                            0
Impulse_Factor                          0
Clearance_Factor                        0
Mean_Absolute_Change                    0
Root_Mean_Square_of_First_Difference    0
Shannon_Entropy                         0
Energy                                  0
Form_Factor                             0
Zero_Crossing_Rate                      0
Turning_Point_Ratio                     0
key                                     0
dtype: int64

In [ ]:
x = df.iloc[: , :-1].values # All columns except last (features)
y= df.iloc[: , -1].values # Last column (target)

In [ ]:
from sklearn.model_selection import train_test_split   #Splitting the dataset into the training set and test set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [ ]:
x[:10 , :20] #Displays the first 10 samples and first 20 features from x

array([[3.13155359e+01, 2.64633910e-02, 2.25524660e-02, 2.08440010e-02,
        8.48379900e-03, 1.13847330e-02, 3.85057570e-02, 2.54523400e-02,
        1.99098290e-02, 1.35757580e-02, 1.01624208e+00, 1.00002904e+00,
        1.01627159e+00, 1.01627159e+00, 6.97770300e-03, 8.46134900e-03,
        3.91199395e+00, 1.96143948e+01, 3.00251174e+01, 5.20000000e-01],
       [3.12584073e+01, 6.42642130e-02, 1.33858320e-02, 1.20849460e-02,
        2.68022860e-02, 4.19382520e-02, 1.70243700e-02, 2.90244510e-02,
        4.47878530e-02, 3.66807410e-02, 1.04558191e+00, 1.00022794e+00,
        1.04582024e+00, 1.04582024e+00, 2.04854410e-02, 2.53617740e-02,
        3.91179479e+00, 1.95506702e+01, 2.81786671e+01, 5.00000000e-01],
       [3.13016786e+01, 5.07457020e-02, 1.22410250e-02, 2.70519970e-02,
        3.93908700e-03, 1.05443920e-02, 3.50278730e-02, 2.73745420e-02,
        2.00113090e-02, 3.27543200e-02, 1.02284054e+00, 1.00004811e+00,
        1.02288975e+00, 1.02288975e+00, 8.65557200e-03, 1.0891

Standardizes features mean=0 and std=1

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_scaled = sc.fit_transform(x)
x_scaled

array([[-0.19729206, -0.63543405, -0.23979303, ...,  0.86679669,
         0.41669098,  0.00798214],
       [-0.7107087 , -0.14909086, -0.37604243, ...,  0.06460175,
        -0.0657092 ,  0.00798214],
       [-0.32182751, -0.32301924, -0.39305841, ...,  0.73384626,
        -0.54810937,  0.00798214],
       ...,
       [ 0.99119592,  0.05063104, -0.03217094, ..., -0.54537151,
        -0.0657092 ,  0.00798214],
       [-0.77181247,  0.97971924,  0.84551795, ..., -0.76720909,
        -0.0657092 ,  0.00798214],
       [-1.18284086, -0.22038915, -0.20280372, ..., -0.42105031,
        -0.54810937,  0.00798214]])

PCA for dimensionality reduction :

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(.90)  # Keep 90% of variance
x_pca = pca.fit_transform(x_scaled)
x_pca

array([[ 2.01533722, -1.14462383,  0.00732158, -0.00704628,  0.42664122],
       [ 0.49448317, -0.72617328, -0.69992965,  0.00419885,  0.05143165],
       [ 1.74918514, -1.01944216, -0.37014765,  0.03167583, -0.48144213],
       ...,
       [-0.6472287 ,  0.80729544,  1.36106546,  0.02440183, -0.41652172],
       [-2.58670802, -1.53970559,  0.51731304,  0.02929902, -0.6259506 ],
       [-0.8979487 , -0.71978322, -1.20461013,  0.0279084 , -0.45304481]])

In [ ]:
pca.explained_variance_ratio_  # these are principle componenets

array([0.56639388, 0.1954819 , 0.04950862, 0.04762542, 0.04398567])

splitting x_scaled (not x_pca) again into training and testing data.

In [ ]:
from sklearn.model_selection import train_test_split   #Splitting the dataset into the training set and test set
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size = 0.3, random_state = True)

Imports and creates a KNN classifier.

Fits the model on training data.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(x_train, y_train)

KNeighborsClassifier()

Predicts on test data and prints both predicted and actual values side-by-side.

In [ ]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[6 6]
 [3 3]
 [2 1]
 ...
 [1 2]
 [1 1]
 [1 2]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[586 149  76   2   0   0]
 [196 556  37   1   0   0]
 [ 27  12 711  18   0   0]
 [  9   6  79 517 147  31]
 [  0   0   3 195 431 166]
 [  0   0   1  88 173 492]]


In [ ]:
new_data_point = [[31.35199043	,0.082313235	,0.024524358	,0.009831822	,0.0129516	,0.001915851	,0.032424806	,0.013826407	,0.008895554	,0.02591079	,1.019788098	,1.000076682	,1.019866297	,1.019866297	,0.011808887	,0.013630612	,3.911946262	,19.66196115	,29.37141829	,0.52	,1]]

transformed_data_point = sc.transform(new_data_point)
predictions = classifier.predict(transformed_data_point)
print(predictions)

[3]


In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.6992992142705458


Accuracy is approx. 70%.