In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/House_Price.csv", header=0)

In [ ]:
df.head()

price  crime_rate  resid_area  air_qual  room_num   age  dist1  dist2  \
0   24.0     0.00632       32.31     0.538     6.575  65.2   4.35   3.81   
1   21.6     0.02731       37.07     0.469     6.421  78.9   4.99   4.70   
2   34.7     0.02729       37.07     0.469     7.185  61.1   5.03   4.86   
3   33.4     0.03237       32.18     0.458     6.998  45.8   6.21   5.93   
4   36.2     0.06905       32.18     0.458     7.147  54.2   6.16   5.86   

   dist3  dist4  teachers  poor_prop airport  n_hos_beds  n_hot_rooms  \
0   4.18   4.01      24.7       4.98     YES       5.480      11.1920   
1   5.12   5.06      22.2       9.14      NO       7.332      12.1728   
2   5.01   4.97      22.2       4.03      NO       7.394     101.1200   
3   6.16   5.96      21.3       2.94     YES       9.268      11.2672   
4   6.37   5.86      21.3       5.33      NO       8.824      11.2896   

  waterbody  rainfall bus_ter     parks  
0     River        23     YES  0.049347  
1      Lake        42     YES  0.046146  
2       NaN        38     YES  0.045764  
3      Lake        45     YES  0.047151  
4      Lake        55     YES  0.039474

In [ ]:
df["airport"] = df["airport"].replace({"YES":1, "NO":0})

<ipython-input-18-7f9844807f45>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["airport"] = df["airport"].replace({"YES":1, "NO":0})


In [ ]:
df = df.drop(['crime_rate', "dist1",	"dist2",	"dist3",	"dist4","waterbody","bus_ter"], axis=1)

In [ ]:
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  airport  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98        1   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14        0   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03        0   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94        1   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33        0   

   n_hos_beds  n_hot_rooms  rainfall     parks  
0       5.480      11.1920        23  0.049347  
1       7.332      12.1728        42  0.046146  
2       7.394     101.1200        38  0.045764  
3       9.268      11.2672        45  0.047151  
4       8.824      11.2896        55  0.039474

In [ ]:
x = df[["price"]]

In [ ]:
y = df["airport"]

In [ ]:
x.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [ ]:
y.head()

0    1
1    0
2    0
3    1
4    0
Name: airport, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(x,y)

LogisticRegression()

In [ ]:
lr.coef_    #b0

array([[0.04317675]])

In [ ]:
lr.intercept_    #b1

array([-0.75390706])

so this model do not use constant term means bo = 0 bydefault

so add constant term into our model

so first add constant to dependent variable

In [ ]:
import statsmodels.api as sn

In [ ]:
x_cons = sn.add_constant(x)

In [ ]:
x_cons.head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [ ]:
import statsmodels.discrete.discrete_model as sm

In [ ]:
logit = sm.Logit(y, x_cons).fit()

Optimization terminated successfully.
         Current function value: 0.670447
         Iterations 5


In [ ]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                airport   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Fri, 03 Jan 2025   Pseudo R-squ.:                 0.02531
Time:                        04:19:01   Log-Likelihood:                -339.25
converged:                       True   LL-Null:                       -348.06
Covariance Type:            nonrobust   LLR p-value:                 2.698e-05
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.7540      0.252     -2.987      0.003      -1.249      -0.259
price          0.0432      0.011      4.010      0.000       0.022       0.064
==============================================================================
"""

### Logistic with multiple predictor :

In [ ]:
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  airport  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98        1   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14        0   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03        0   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94        1   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33        0   

   n_hos_beds  n_hot_rooms  rainfall     parks  
0       5.480      11.1920        23  0.049347  
1       7.332      12.1728        42  0.046146  
2       7.394     101.1200        38  0.045764  
3       9.268      11.2672        45  0.047151  
4       8.824      11.2896        55  0.039474

In [ ]:
x = df.loc[:, df.columns != "airport"]

In [ ]:
y = df["airport"]

In [ ]:
column_means = x.mean()
x = x.fillna(column_means)
lr.fit(x, y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  airport  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98        1   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14        0   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03        0   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94        1   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33        0   

   n_hos_beds  n_hot_rooms  rainfall     parks  
0       5.480      11.1920        23  0.049347  
1       7.332      12.1728        42  0.046146  
2       7.394     101.1200        38  0.045764  
3       9.268      11.2672        45  0.047151  
4       8.824      11.2896        55  0.039474

In [ ]:
lr = LogisticRegression()

In [ ]:
df.isnull().sum()

price          0
resid_area     0
air_qual       0
room_num       0
age            0
teachers       0
poor_prop      0
airport        0
n_hos_beds     8
n_hot_rooms    0
rainfall       0
parks          0
dtype: int64

In [ ]:
lr.fit(x,y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
lr.coef_

array([[ 0.05609408, -0.04190462, -0.02327326,  0.22909294,  0.00946376,
        -0.04710627,  0.0334705 , -0.03158859, -0.04071967, -0.00083413,
         0.00169136]])

In [ ]:
lr.intercept_

array([0.01832102])

In [ ]:
x_cons = sn.add_constant(x)

In [ ]:
logit = sm.Logit(y, x_cons).fit()

Optimization terminated successfully.
         Current function value: 0.654724
         Iterations 6


In [ ]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                airport   No. Observations:                  506
Model:                          Logit   Df Residuals:                      494
Method:                           MLE   Df Model:                           11
Date:                Fri, 03 Jan 2025   Pseudo R-squ.:                 0.04817
Time:                        04:27:39   Log-Likelihood:                -331.29
converged:                       True   LL-Null:                       -348.06
Covariance Type:            nonrobust   LLR p-value:                 0.0004315
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -0.0485      1.977     -0.025      0.980      -3.923       3.826
price           0.0539      0.020      2.732      0.006       0.015       0.093
resid_area     -0.0391      0.023     -1.673      0.094      -0.085       0.007
air_qual       -2.0373      2.325     -0.876      0.381      -6.595       2.521
room_num        0.2392      0.196      1.220      0.222      -0.145       0.623
age             0.0103      0.005      1.951      0.051   -4.51e-05       0.021
teachers       -0.0457      0.053     -0.864      0.388      -0.149       0.058
poor_prop       0.0326      0.024      1.363      0.173      -0.014       0.079
n_hos_beds     -0.0315      0.064     -0.490      0.624      -0.157       0.094
n_hot_rooms    -0.0418      0.031     -1.328      0.184      -0.103       0.020
rainfall       -0.0009      0.007     -0.115      0.908      -0.015       0.014
parks          18.2000     21.799      0.835      0.404     -24.525      60.925
===============================================================================
"""

## Predicting and confusion matrix

In [ ]:
lr.predict_proba(x)  # 1st column represents "false", and 2nd column is prob. of hanpening "true"

array([[0.38304128, 0.61695872],
       [0.40582408, 0.59417592],
       [0.93516618, 0.06483382],
       ...,
       [0.3437883 , 0.6562117 ],
       [0.42615443, 0.57384557],
       [0.48675511, 0.51324489]])

In [ ]:
y_pred = lr.predict(x)
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,

In [ ]:
Y_pred3 = (lr.predict_proba(x)[:,1] >=0.3).astype(bool)

In [ ]:
Y_pred3

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y, y_pred)

array([[105, 122],
       [ 76, 203]])

## Evaluating the performance

precision = tp/(tp+fp)

recall = tp/(tp+fn)

AUC(ROC), AUC = area under the curve means performance of the model

In [ ]:
from sklearn.metrics import precision_score, recall_score, roc_auc_score

In [ ]:
precision_score(y,y_pred)

0.6246153846153846

In [ ]:
recall_score(y,y_pred)

0.7275985663082437

In [ ]:
roc_auc_score(y, y_pred)

0.5950768161937695

# Linear Discriminant Analysis (LDA) :

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
lda = LinearDiscriminantAnalysis()

In [ ]:
lda.fit(x,y)

LinearDiscriminantAnalysis()

In [ ]:
y_pred_lda = lda.predict(x)

In [ ]:
y_pred_lda

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [ ]:
confusion_matrix(y, y_pred_lda)

array([[109, 118],
       [ 77, 202]])